const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const source = fs.readFileSync(require('node:path').join(__dirname,'../public/app.js'),'utf8').replace("import { config } from './config.js';",'const config = {};');
for (const height of [600,1080,2160]) {
  let strokes=0, frame;
  const noop=()=>{};
  const context={clearRect:noop,beginPath:noop,arc:noop,fill:noop,moveTo:noop,lineTo:noop,stroke:()=>strokes++};
  const elements=new Map();
  const element=id=>{ if(!elements.has(id)) elements.set(id,{textContent:'',style:{},classList:{add:noop,remove:noop},setAttribute:noop,addEventListener:noop,getContext:()=>context}); return elements.get(id); };
  const sandbox={document:{getElementById:element,querySelector:element,addEventListener:noop},location:{hostname:'example.com'},window:{addEventListener:noop},innerWidth:1920,innerHeight:height,Intl,Date,Math,AbortSignal,HTMLInputElement:class{},HTMLTextAreaElement:class{},matchMedia:()=>({matches:false}),setTimeout:fn=>{fn();return 1;},clearTimeout:noop,setInterval:noop,addEventListener:noop,requestAnimationFrame:fn=>frame=fn};
  sandbox.document.querySelectorAll = () => [];
  vm.createContext(sandbox); vm.runInContext(source,sandbox); vm.runInContext('launchFireworks()',sandbox);
  for(let i=0;i<700;i++)frame();
  assert(strokes>10000,`No full bursts at height ${height}`);
  assert.equal(vm.runInContext('rockets.length + particles.length',sandbox),0,'Particles must finish');
  console.log(`PASS: fireworks burst and finish at ${height}px (${strokes} spark strokes)`);
  sandbox.document.body = {classList:{toggle:noop}};
  vm.runInContext('setAchieved(true)',sandbox);
  assert.equal(element('remaining').textContent,'100%');
  for(let i=0;i<1800;i++)frame(i*16.667);
  assert(vm.runInContext('rockets.length + particles.length > 0',sandbox),'Finale must keep running');
  assert(vm.runInContext('particles.length <= 3600 && rockets.length <= 40',sandbox),'Effects must remain bounded');
  vm.runInContext('remaining=12;setAchieved(false)',sandbox);
  assert.equal(element('remaining').textContent,12);
  assert.equal(vm.runInContext('rockets.length + particles.length',sandbox),0);
  console.log('PASS: continuous achievement finale, bounded particles, and return to countdown');
  let starts = 0;
  const param = {setValueAtTime:noop,linearRampToValueAtTime:noop,exponentialRampToValueAtTime:noop};
  const audioNode = () => ({connect:noop,disconnect:noop,start:()=>starts++,stop:noop,gain:{...param},frequency:{...param},pan:{value:0}});
  sandbox.testAudio = {state:'running',currentTime:1,createStereoPanner:audioNode,createBufferSource:audioNode,createBiquadFilter:audioNode,createGain:audioNode,createOscillator:audioNode};
  vm.runInContext('audioContext=testAudio;audioMaster={};fireworksBuffer={duration:2};cheeringBuffer={duration:17};soundEnabled=true;playFireworkSound(.2);playFireworkSound(.8)',sandbox);
  assert.equal(starts,2,'Only one fireworks/cheering pair within throttle window');
  sandbox.testAudio.currentTime=2; sandbox.document.hidden=true;
  vm.runInContext('playFireworkSound(.5)',sandbox);
  assert.equal(starts,2,'Hidden page stays silent');
  sandbox.document.hidden=false;
  vm.runInContext('soundEnabled=false;playFireworkSound(.5)',sandbox);
  assert.equal(starts,2,'Muted page stays silent');
  console.log('PASS: recorded audio mix, rate limit, hidden-page silence, and mute');
}
